### ISSUE TITLE
operation not permitted

### ISSUE THREAD

**Issue by ItzAmirreza** [RayFernando1337/LLM-Calc#17]
```
  VITE v5.4.10  ready in 1257 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
17672 | let sameCount = 0;
17673 | function clearScreen() {
17674 |   const repeatCount = process.stdout.rows - 2;
17675 |   const blank = repeatCount > 0 ? "\n".repeat(repeatCount) : "";
17676 |   console.log(blank);
17677 |   readline.cursorTo(process.stdout, 0, 0);
        ^
EPERM: Operation not permitted
   errno: -1
 syscall: "write"
      fd: 74

      at write (native:1:1)
      at NativeWritablePrototypeWrite (node:stream:3671:38)
      at clearScreen (/home/mf/LLM-Calc/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:17677:12)
      at output (/home/mf/LLM-Calc/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:22498:9)
      at info (/home/mf/LLM-Calc/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:22517:5)
      at /home/mf/LLM-Calc/node_modules/vite/dist/node/cli.js:894:25
      at processTicksAndRejections (native:7:39)

Bun v1.1.34 (Linux x64)
error: "vite" exited with code 1
error: script "dev" exited with code 1
mf@mfscape:~/LLM-Calc$ bun installbun run build
error: Script not found "installbun"
mf@mfscape:~/LLM-Calc$ bun run build
$ bun run vite build
vite v5.4.10 building for production...
18020 |   } else {
18021 |     process.stdout.write(output.substring(0, process.stdout.columns - 1));
18022 |   }
18023 | }
18024 | function clearLine$1() {
18025 |   process.stdout.clearLine(0);
        ^
EPERM: Operation not permitted
   errno: -1
 syscall: "write"
      fd: 15

      at write (native:1:1)
      at NativeWritablePrototypeWrite (node:stream:3671:38)
      at clearLine$1 (/home/mf/LLM-Calc/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:18025:18)
      at writeLine (/home/mf/LLM-Calc/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:23290:46)
      at /home/mf/LLM-Calc/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:22654:9
      at /home/mf/LLM-Calc/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:23320:1
      at transform (/home/mf/LLM-Calc/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:22722:3)
      at /home/mf/LLM-Calc/node_modules/rollup/dist/es/shared/node-entry.js:20760:40
      at processTicksAndRejections (native:7:39)

Bun v1.1.34 (Linux x64)
error: "vite" exited with code 1
error: script "build" exited with code 1


```
This happens after the command bun run dev

**Comment by RayFernando1337** [comment]
The errors are related to writing to the console. What commands/how did you use to install the repo on your machine? Any issues when installing dependencies?

**Update dependencies**:
   Make sure all dependencies are up to date:
   ```
   bun install
   ```


**Check file permissions**:
   Ensure that your user has the necessary permissions to access and modify files in the project directory:
Also the output of
```
sudo chown -R $(whoami) /path/to/LLM-Calc
```

**Workarounds**
Remove & Re-install dependencies. 

```
sudo chown -R $USER:$GROUP ./node_modules
```

**Comment by ItzAmirreza** [comment]
Thank you
